name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hey **#** welcome to this repoThanks for your time and contribution to this project.'' first issue'
        pr-message: 'Hey **#** welcome to this repo. Thanks for your time and contribution to this project.'' first pr'
